name: DominikSteinacher
favicon: null
layout_spectrum: 0.48635
typography_spectrum: 0.07885305
title: This is me
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#fff9ea'
    - '#252527'
    - '#e7a468'
    - '#6d6865'
  brandStrength: 0.765233
  lightness: 0.4444444
  saturation: 0.6218638
  rhythmicContrast: 0.5519713
purpose: []
